create or replace TRIGGER trg_set_notification_id
BEFORE INSERT ON ENC_NOTIFICATIONS
FOR EACH ROW
BEGIN
    IF :NEW.NTS_NOTIFICATION_ID IS NULL THEN
        SELECT ENC_NOTIFICATIONS_SEQ.NEXTVAL INTO :NEW.NTS_NOTIFICATION_ID FROM DUAL;
    END IF;
END;
/