create or replace TRIGGER TRG_NOTIFY_EVENT_UPDATE
AFTER UPDATE OF EVS_TITLE, EVS_EVENT_DATE, EVS_LOCATION ON ENC_EVENTS
FOR EACH ROW
BEGIN
    INSERT INTO ENC_NOTIFICATIONS (NTS_NOTIFICATION_ID, USR_ID, EVS_EVENT_ID, NTS_TITLE, NTS_MESSAGE)
    SELECT ENC_NOTIFICATIONS_SEQ.NEXTVAL, P.USR_ID, :NEW.EVS_EVENT_ID,  
           'Evenement gewijzigd',
           'Het evenement "' || :NEW.EVS_TITLE || '" is gewijzigd. Bekijk de details in de app.'
    FROM ENC_REGISTRATIONS P
    WHERE P.EVS_EVENT_ID = :NEW.EVS_EVENT_ID;
END;
/